### ISSUE TITLE
TypeError: this.timer.unref is not a function

### ISSUE THREAD

**Issue by mrapczynski** [iccicci/rotating-file-stream#12]
I use `rotating-file-stream` as a dependency in a custom logging framework, but I have not tested the rolling file behavior much because we send a good amount of log data to Splunk. I cannot reproduce the following in test cases for our framework, but when I add our framework to a real application, the following errors from `rotating-file-stream` start appearing.

Any ideas?

Using package version 1.2.2, with Node 7.9.0

```
TypeError: this.timer.unref is not a function
    at RotatingFileStream.interval (/Users/mrapczynski/Development/Node/Applications/BSIS Next Gen/node_modules/fhda-pubsub-logging/node_modules/rotating-file-stream/interval.js:56:13)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at RotatingFileStream.emit (events.js:188:7)
    at WriteStream.<anonymous> (/Users/mrapczynski/Development/Node/Applications/BSIS Next Gen/node_modules/fhda-pubsub-logging/node_modules/rotating-file-stream/index.js:252:8)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at WriteStream.emit (events.js:191:7)
    at WriteStream.<anonymous> (fs.js:2043:10)
    at FSReqWrap.oncomplete (fs.js:114:15)
```

**Comment by iccicci** [comment]
Hi,

no idea yet... let me investigate a while.

Thank you

**Comment by mrapczynski** [comment]
I found the problem by accident while looking through other GH issues. The issue stems from using Jest as a test runner (which I am doing). Jest needs to be told explicitly a Node environment is wanted. Turns off the JSDOM web stuff that messes with timer objects.

`jest --env=node tests-jest/.*`

We are good, no issue with the library. Thanks!

**Comment by iccicci** [comment]
Great!

Thank you again.
