### ISSUE TITLE
Not rotating by intrerval or size

### ISSUE THREAD

**Issue by adrian-badulescu** [iccicci/rotating-file-stream#65]
Hi, 
I have this error every time is creating a new compressed file
```events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, stat 'C:\Users\cj68qe\Desktop\backend NSIA\logs\data.log'
Emitted 'error' event on RotatingFileStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:424:5)
    at onwrite (_stream_writable.js:445:5)
    at destroy (C:\Users\cj68qe\Desktop\backend NSIA\node_modules\rotating-file-stream\index.js:75:20)
    at C:\Users\cj68qe\Desktop\backend NSIA\node_modules\rotating-file-stream\index.js:109:28
    at FSReqCallback.oncomplete (fs.js:168:21) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'stat',
  path: 'C:\\Users\\cj68qe\\Desktop\\backend NSIA\\logs\\data.log'
}
[nodemon] app crashed - waiting for file changes before starting...```

my code:
const express = require('express')
const helmet = require("helmet");
const app = express();
const fs = require('fs');
const morganBody = require('morgan-body')
const morgan = require('morgan');
const path = require('path');
var mustacheExpress = require('mustache-express');
const bodyParser = require('body-parser');
const { logger, timeStamp } = require('./logger')
const api = require('./api')
const form = require('./form')
const cors = require('cors')
const compression = require('compression');
const port = (process.env.PORT || 8080);
var rfs = require('rotating-file-stream');
const log = fs.createWriteStream(
  path.join(__dirname, "logs", "data.log"), { flags: "a" }
);

// var accessLogStream = rfs.createStream('access.log', {
//   size: '10M', // rotate 10 Megs
//   compress: "gzip",
//   path: path.join(__dirname, '/logs')
// })
var dataLogStream = rfs.createStream('data.log', {
  size: '2K', // rotate 10 Megs,
  interval: '5s',
  compress: "gzip",
  path: path.join(__dirname, '/logs')
})

// deactivate CORS
app.use(cors())

app.use(helmet())
app.use(compression())
// Mustache middleware
app.engine('mustache', mustacheExpress());
app.set('view engine', 'mustache');
app.set('views', `${__dirname}/views`);


app.use(bodyParser.urlencoded({ extended: true }))
app.use(bodyParser.json())
// middleware logger
app.use(logger)
// middleware to log and add time stamp
app.use(timeStamp)
// setup the logger
// app.use(morgan('combined', { stream: accessLogStream }))

morganBody(app, {  
  noColors: true,
  stream: dataLogStream,
});
// APIS for new UAT & new ST
app.use('/api',api) 

// API for sending SSR form serialized
app.use('/form', form)





app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})

**Comment by adrian-badulescu** [comment]
My bad, it was because of 
const log = fs.createWriteStream(
  path.join(__dirname, "logs", "data.log"), { flags: "a" }
);

**Comment by iccicci** [comment]
You are welcome anyway @adrian-badulescu 😃
