### ISSUE TITLE
Cannot find module 'fs/promises'  

### ISSUE THREAD

**Issue by minato37103710** [iccicci/rotating-file-stream#82]
```
internal/modules/cjs/loader.js:670
throw err;
Error: Cannot find module 'fs/promises'
at Function.Module._resolveFilename
(internal/modules/cjs/loader.js:668:15)
at Function.Module._load
(internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/admin/node_modules/rotating-file-stream/dist/cjs/index.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
```

**Comment by iccicci** [comment]
Sorry, there is an error in the [compatibility](https://github.com/iccicci/rotating-file-stream#compatibility) section of the documentation.
Actually Nove v14 is required.

**Comment by minato37103710** [comment]
I see. .....
Is it available in v11.15.0?

**Comment by iccicci** [comment]
You could try with an older version of this package: I suggest v2.1.6
Please take a look at the [tags](https://github.com/iccicci/rotating-file-stream/tags) if you can try a version working with older Node.js versions.

Hope this helps.

P.S.
Please write in English

**Comment by minato37103710** [comment]
> Please write in English

sorry I'm Japanese and I'm using deepl translation, but I think my settings were wrong!

> You could try with an older version of this package: I suggest v2.1.6
Please take a look at the [tags](https://github.com/iccicci/rotating-file-stream/tags) if you can try a version working with older Node.js versions.

ok　Understood.

**Comment by iccicci** [comment]
Hi @minato37103710 , was you able to solve your problem?

**Comment by iccicci** [comment]
Closed due to lack of feedback
